name: molGenEnv
channels:
  - conda-forge
  - defaults
  - rdkit
dependencies:
  # Linters
  - black
  - flake8
  - isort
  - mypy
  - pre-commit

  # Testing
  - pytest
  - pytest-mock

  # Python
  - python=3.9

  # Libraries
  - attrs
  - dask
  - fastparquet
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pyprojroot
  - rdkit
  - selfies
  - tqdm

  # src/mol_gen/
  - pip~=22.0
  - pip:
    - tensorflow-gpu==2.8
    - -e .
