name: molGenEnv
channels:
  - conda-forge
  - defaults
  - rdkit
dependencies:
  - black
  - flake8
  - isort
  - mypy
  - pytest
  - pytest-mock


  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - python=3.8
  - rdkit
  - tensorflow
  - tqdm
