name: molGenEnv
channels:
  - conda-forge
  - defaults
  - nvidia
  - rdkit
dependencies:
  # Linters
  - black
  - flake8
  - isort
  - mypy
  - pre-commit

  # Testing
  - pytest
  - pytest-mock

  # Python
  - python=3.10

  # Libraries
  - attrs
  - cudnn=8.2
  - cudatoolkit=11.2
  - dask
  - fastparquet
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - papermill
  - pyprojroot
  - rdkit
  - selfies

  - pip~=22.0
  - pip:
    - tensorflow-gpu==2.8
    # Tensorflow - TypeError: Descriptors cannot not be created directly.
    - protobuf~=3.19.0
    # src/mol_gen/
    - -e .
