name: molGenEnv
channels:
  - conda-forge
  - defaults
  - rdkit
dependencies:
  - black
  - flake8
  - isort
  - mypy
  - pre-commit
  - pytest
  - pytest-mock

  - attrs
  - dask
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - python=3.9
  - rdkit
  - tensorflow
  - tqdm

  - pip~=22.0
  - pip:
    - -e .
