dataset:
    buffer_size: 1000000
    batch_size: 2048
model:
    embedding_dim: 64
    lstm_layers:
        - units: 128
          dropout: 0.5
    patience: 5
    epochs: 100
evaluate:
    n_molecules: 1024
    subset_size: 100
